/*
 * @Description: What's this for
 * @Autor: WangYuan1
 * @Date: 2024-07-26 15:04:35
 * @LastEditors: WangYuan
 * @LastEditTime: 2024-10-24 10:33:22
 */
export default {
  UseType: [
    { label: "教育", value: "education" },
    { label: "美食", value: "food" },
    { label: "旅游", value: "travel" },
    { label: "节日", value: "festival" },
    { label: "娱乐", value: "recreation" },
    { label: "动漫", value: "cartoon" },
    { label: "电商", value: "mall" },
    { label: "其他", value: "other" },
  ],
  RateObject: {
    1: "非常不满意",
    2: "比较不满意",
    3: "一般",
    4: "比较满意",
    5: "非常满意",
  },
  iconfont: [
    {
      title: "线面常用",
      list: [
        "icon-a-064_anquan",
        "icon-a-064_diannao",
        "icon-a-064_huishou",
        "icon-a-064_shizhong",
        "icon-a-064_sixin",
        "icon-a-064_waisong",
        "icon-a-064_xiazai",
        "icon-a-064_zhibo",
        "icon-a-064_yuyin",
        "icon-a-064_duihua-06",
        "icon-a-064_dingwei",
        "icon-a-064_gengduo",
        "icon-a-064_wendang-02",
        "icon-a-064_wendang-22",
        "icon-a-064_wenjian",
        "icon-shuqian",
        "icon-biaoji-grey",
        "icon-a-064_baohu",
        "icon-a-064_biaoji-44",
        "icon-a-064_biaoqian-12",
        "icon-a-064_biaoqing",
        "icon-a-064_diqiu",
        "icon-a-064_duihua-46",
        "icon-a-064_faxian",
        "icon-a-064_gongyuan",
        "icon-a-064_gouwuche",
        "icon-a-064_huodong",
        "icon-a-064_luyin",
        "icon-a-064_huore",
        "icon-a-064_lvhua",
        "icon-a-064_jifen-41",
        "icon-a-064_saoma-33",
        "icon-a-064_shuben",
        "icon-a-064_shuidi",
        "icon-a-064_shezhi",
        "icon-a-064_shuxie",
        "icon-a-064_tixing",
        "icon-a-064_wenben",
        "icon-a-064_wode",
        "icon-a-064_xiangfa",
        "icon-a-064_yinle-11",
        "icon-a-064_xiaoshuai",
        "icon-a-064_sousuo",
        "icon-a-064_xindong",
        "icon-a-064_yinle-39",
        "icon-a-064_zhaopian",
        "icon-a-064_zhuye",
        "icon-a-064_zhishi",
      ],
    },
  ],
  widgetTypeList: [
    {
      group: "基础",
      icon: "components-eohf28lk",
      list: [],
    },
    {
      group: "容器",
      icon: "box-eohf2p84",
      list: [],
    },
    {
      group: "自定义",
      icon: "cross-ring-two",
      list: [],
    },
    {
      group: "表单",
      icon: "align-text-left-one",
      list: [],
    },
    {
      group: "详情",
      icon: "align-text-left-one",
      list: [],
    },
    {
      group: "其他",
      icon: "components-eohf28lk",
      list: [],
    },
  ],
};
